### ISSUE TITLE
Cannot login on a page with an anchor when the  user's session has expired

### ISSUE THREAD

**Issue by oanat** [xwikisas/integration-azure-oauth#32] opened 2023-10-13 14:50 UTC
Steps to reproduce:
* Setup XWiki 14.10.18 and Azure AD Pro 1.7.1
* Create a page with the content below
 ```
{{toc numbered="true" start="2"/}}

== A heading ==

    Some text.

== Another heading ==

    More text.
```
*  (Optional) Remove the guest view rights on the wiki by ticking "Prevent unregistered users from viewing pages, regardless of the page rights " from the Global Administration: Rights (this means that the login will be required when you open the anchor links, I tried waiting for the session to expire but it takes too long)
* Open the anchor links created by the toc macro from the test page in a private/incognito window 
* Click to login

Result:
* Clicking on "Login with Azure Active Directory" has no effect
* The generated link is http://localhost:8080/xwiki/bin/login/XWiki/XWikiLogin?srid=ZHIvS6H2&xredirect=%2Fxwiki%2Fbin%2Fview%2FSandbox%2FTestPage%2F%3Fsrid%3DZHIvS6H2#HAheading&identityOAuth=start&browserLocation=http%3A//localhost%3A8080/xwiki/bin/login/XWiki/XWikiLogin&provider=AzureAD
* I encountered the same behaviour later on when I opened the toc link in a new tab and the session expired

Expected result:
* Clicking on "Login with Azure Active Directory" redirects to the Microsoft page to fill in the credentials

**Comment by oanalavinia** [comment] 2023-10-31 11:38
Closed as part of https://github.com/xwikisas/integration-azure-oauth/issues/33, which includes the fix of the root cause https://github.com/xwikisas/identity-oauth/issues/38

**Closed by oanalavinia** 2023-10-31 11:38 UTC
Labels: Type: Bug, Priority : Major
